### ISSUE TITLE
heavy cpu load

### ISSUE THREAD

**Issue by tristan-k** [arranger1044/iSoul#7]
I'm on Lion (10.7) and will get some heavy cpu load when running the latest iSoul binary (around 67,3%). Any suggestions?

**Comment by arranger1044** [comment]
I've not tested it on Lion (I'm on SL at the moment), but some users reported that the same happens under Leopard sometimes.
Have you got XCode and Instruments installed?

**Comment by djbe** [comment]
I've got Lion installed, I'll take a look at it.

Did you pay attention to when it starts to display this behavior? Right from the start? When chatting?

**Comment by interconnect** [comment]
I'm seeing this issue as well on 10.7.0 Lion.  Immediately upon launch (at idle/no transfers) i'm getting ~70% CPU load.

**Comment by arranger1044** [comment]
Any clue about it, David?

**Comment by ironcrosser** [comment]
I confirm the CPU load on Lion on all 3 BETA versions (4.0b , 4.1b, 4.2b), shortly after launch my CPU reaches around 115% !!! and fans runs at full speed - Macbook Pro mid 2009

**Comment by interconnect** [comment]
Is this app going to get an update soon?  It runs well on Lion, except for the high CPU load issue.  Would love to see this get resolved!!

**Comment by djbe** [comment]
I took a look at it during the summer, updated a bunch of libs, used instruments to see what was taking a lot of CPU time, but... no bloody idea. Should I have some time next weekend I'll give it a new try, but no promesses.

**Comment by Breakster** [comment]
I just compiled the iSoul version from the google code website for Lion 10.7.2 (@ arranger: thanks for pointing out the dependency issue). TBH, I am not using this version because I am suffering from the heavy cpu load as well. Moreover, I don't have many issues with the google code branch. So I am wondering what are the main differences between the google code version and this version.

**Comment by arranger1044** [comment]
The Lion heavy CPU usage is the major issue we have at the moment.

@Breakster this is a small list of some small changes (improvements?) so far:
- Some changes to the user interface:
  - The network connection icon is now a green light when you are connected to the soulseek network and a red one when you are disconnected (improved usability when you can't connect to the museek daemon)
  - Changed the location of the search bar and added a button in the toolbar to get the chat room list appear
  - Now each chat view has its own divider position
  - Saving of the last used search view style, and disabling of the controller when it cannot be used
  - Downloading/uploading connections now have more statuses displayed (improved usability when a connection error occurs)
  - Others (even) lesser improvements in the size and animation of views (ie. Added animation transitions when hiding the user list in a chat view or passing between two chat view with different user list sizes)
    - Properly displaying unread chat messages counters
- Added integration with the Growl framework
- Added a Console that displays what the app is doing (plus much log spam at the moment)
- Added a search option in the chat room list window
- Fixed a bug in the removing of a search item
- Fixed the incrementing/decrementing counter associated to downloads/uploads
- Fixed the chat counters, now they display unread messages for that chat and not the number of users in that chat
- Added a logging framework that will save the Console output in a gzipped file (under ~/Library/Logs/Rainbow as the default folder changeable from the preferences) this will be quite useful for debugging and gathering data in the future.
- Updated libevent and the port mapper preventing a bug in the early connection

I recognize that all of this is just _minor_ improvements, but it makes iSoul being more usable everyday as a default soulseek client to me and David

**Comment by djbe** [comment]
Allright so I tried going back all the way to the first git commit, but unfortunately that one doesn't compile, namely the museek library/executable/whatever gives me a few compile errors. This is disregarding all the other compile errors due to old project settings that got changed at a later date.

I then went further to the first commit where museek was updated. That one compiles after a few project changes, but that commit also displays the 100% CPU usage. So it's something before that :-(  I'll try going back to the first commit and modifying the museek library so that it compiles, and see if the problem is still there.

Were any changes made between the last svn version and the first git commit?

**Comment by djbe** [comment]
Woot, found the code responsible for this!

I finally got the first commit to compile & run, and noticed the log printing "received notification" like a bloody maniac, so THAT was the problem: the log was being overloaded by notifications. I'm going to disable the logging code for now, until a better logging solution is found, i.e. not logging everything :-P

**Comment by interconnect** [comment]
Awesome! Maybe we could get a new build in the meantime until it's fixed up proper?

**Comment by djbe** [comment]
Sure thing. But I want to stop putting releases in the repository, got to find a new place to put them.
I'll ask mr.resistor if we can get access to his macupdate account or something.

Edit: see the [downloads](https://github.com/arranger1044/iSoul/downloads) page.

**Comment by interconnect** [comment]
Is the 0.4.3 build in the downloads area the latest one?

**Comment by djbe** [comment]
Yes it is (look at the date).

**Comment by arranger1044** [comment]
Very good job David!
interconnect and ironcrosser test the new release please

**Comment by ironcrosser** [comment]
this upload don't have the "releases" folder that contained the executable "iSoul", how can I run it?

**Comment by djbe** [comment]
A) This isn't the place for this discussion. If you have an issue with something, and it's not related to this one, please create a new one.

B) What on earth are you talking about? Go to the downloads page, download the latest version (in this case 0.4.3), unzip it and then run it.

**Comment by ironcrosser** [comment]
You are right, I mistakenly clicked the "download the Zip file" instead of the "iSoul v0.4.3.zip", my bad...
